Author.find_or_create_by(name: "J. K. Rowling")
Author.find_or_create_by(name: "Mary GrandPré")
Author.find_or_create_by(name: "Rowling, J.K.")
Author.find_or_create_by(name: "John Tiffany")
Author.find_or_create_by(name: "Jack Thorne")
Author.find_or_create_by(name: "John Ronald Reuel Tolkien")
Author.find_or_create_by(name: "J. R. R. Tolkien")
Author.find_or_create_by(name: "John Grisham")
Author.find_or_create_by(name: "George Orwell")
Author.find_or_create_by(name: "Patrick Rothfuss")
Author.find_or_create_by(name: "Nate Taylor")
Author.find_or_create_by(name: "Jane Austen")
Author.find_or_create_by(name: "Margaret Drabble")
Author.find_or_create_by(name: "Laura Engel")
Author.find_or_create_by(name: "Gillian Beer")
Author.find_or_create_by(name: "Michael Crichton")
Author.find_or_create_by(name: "Gail Herman")
Author.find_or_create_by(name: "Jeffrey Hudson")
Author.find_or_create_by(name: "Tana French")
Author.find_or_create_by(name: "Stephanie Coontz")
Author.find_or_create_by(name: "N. K. Jemisin")
Author.find_or_create_by(name: "Joseph Heller")
Author.find_or_create_by(name: "Anthony Doerr")
Author.find_or_create_by(name: "Joe Hill")
Author.find_or_create_by(name: "Jason Ciaramella")
Author.find_or_create_by(name: "Gabriel Rodriguez")
Author.find_or_create_by(name: "Gabriel Rodríguez")
Author.find_or_create_by(name: "Trevor Noah")
Author.find_or_create_by(name: "Thomas Mullen")
Author.find_or_create_by(name: "Matthew Desmond")
Author.find_or_create_by(name: "Kiersten White")
Author.find_or_create_by(name: "Dan Brown")
Author.find_or_create_by(name: "Thomas Harris")
Author.find_or_create_by(name: "ignacio sanabria")
Author.find_or_create_by(name: "L. G. Minasean")
Author.find_or_create_by(name: "John Irving")
Author.find_or_create_by(name: "John Marsden")
Author.find_or_create_by(name: "Megan Whalen Turner")
Author.find_or_create_by(name: "Joe Biden")
Author.find_or_create_by(name: "Barack Obama")
Author.find_or_create_by(name: "James S.A. Corey")
Author.find_or_create_by(name: "James S. A. Corey")
Author.find_or_create_by(name: "Garth Nix")
Author.find_or_create_by(name: "Brandon Sanderson")
Author.find_or_create_by(name: "Robert Jordan")
Author.find_or_create_by(name: "Reagan O'Neal")
Author.find_or_create_by(name: "Richard Phillips Feynman")
Author.find_or_create_by(name: "Ralph Leighton")
Author.find_or_create_by(name: "James Gleick")
Author.find_or_create_by(name: "Ray Kurzweil")
Author.find_or_create_by(name: "Dorothy Dunnett")
Author.find_or_create_by(name: "Roger Zelazny")
Author.find_or_create_by(name: "Jennifer Egan")
Author.find_or_create_by(name: "Jim Butcher")
Author.find_or_create_by(name: "Daniel Keyes")
Author.find_or_create_by(name: "Erin Morgenstern")
Author.find_or_create_by(name: "Robin Hobb")
Author.find_or_create_by(name: "Emily St. John Mandel")
Author.find_or_create_by(name: "Dan Simmons")
Author.find_or_create_by(name: "Kurt Vonnegut")
Author.find_or_create_by(name: "Philip Pullman")
Author.find_or_create_by(name: "Caleb Carr")
Author.find_or_create_by(name: "Agatha Christie")
Author.find_or_create_by(name: "Neal Stephenson")
Author.find_or_create_by(name: "Randy Shilts")
Author.find_or_create_by(name: "Jonathan Haidt")
Author.find_or_create_by(name: "W. Timothy Gallwey")
Author.find_or_create_by(name: "Siddhartha Mukherjee")
Author.find_or_create_by(name: "David Sedaris")
Author.find_or_create_by(name: "Sidney Bechet")
Author.find_or_create_by(name: "Paula Hawkins")
Author.find_or_create_by(name: "Maya Angelou")
Author.find_or_create_by(name: "Harry Markopolos")
Author.find_or_create_by(name: "Richard Llewellyn")
Author.find_or_create_by(name: "Lev Grossman")
Author.find_or_create_by(name: "Brian Herbert")
Author.find_or_create_by(name: "Frank Herbert")
Author.find_or_create_by(name: "Bill Ransom")
Author.find_or_create_by(name: "Janet Asimov")
Author.find_or_create_by(name: "Isaac Asimov")
Author.find_or_create_by(name: "Suzanne Collins")
Author.find_or_create_by(name: "Veronica Roth")
Author.find_or_create_by(name: "Daniel Abraham")
Author.find_or_create_by(name: "George R. R. Martin")
Author.find_or_create_by(name: "Terry Goodkind")
Author.find_or_create_by(name: "Christopher Hitchens")
Author.find_or_create_by(name: "Jacqueline Susann")
Author.find_or_create_by(name: "Jeffrey Eugenides")
Author.find_or_create_by(name: "春樹·村上")
Author.find_or_create_by(name: "Haruki Murakami")
Author.find_or_create_by(name: "Isabel Allende")
Author.find_or_create_by(name: "Anita Diamant")
Author.find_or_create_by(name: "Audrey Niffenegger")
Author.find_or_create_by(name: "Sylvia Plath")
Author.find_or_create_by(name: "Evelyn Waugh")
Author.find_or_create_by(name: "David Vann")
Author.find_or_create_by(name: "Christopher Moore")
Author.find_or_create_by(name: "Patricia A. McKillip")
Author.find_or_create_by(name: "Pierce Brown")
Author.find_or_create_by(name: "Carl Sagan")
Author.find_or_create_by(name: "Terry Pratchett")
Author.find_or_create_by(name: "Neil Gaiman")
Author.find_or_create_by(name: "Margaret Atwood")
Author.find_or_create_by(name: "Ursula K. Le Guin")
