Genre.find_or_create_by(name: "Fiction")
Genre.find_or_create_by(name: "Science fiction")
Genre.find_or_create_by(name: "Suspense")
Genre.find_or_create_by(name: "Historical fiction")
Genre.find_or_create_by(name: "History")
Genre.find_or_create_by(name: "Murder")
Genre.find_or_create_by(name: "Humor")
Genre.find_or_create_by(name: "Biography")
Genre.find_or_create_by(name: "Satire")
Genre.find_or_create_by(name: "Mystery")
Genre.find_or_create_by(name: "Young adult fiction")
Genre.find_or_create_by(name: "Adventure")
Genre.find_or_create_by(name: "Autobiography")
Genre.find_or_create_by(name: "Fantasy")
Genre.find_or_create_by(name: "Dystopias")
Genre.find_or_create_by(name: "Non-fiction")
Genre.find_or_create_by(name: "Children's books")
Genre.find_or_create_by(name: "Action")
Genre.find_or_create_by(name: "Thriller")
Genre.find_or_create_by(name: "Political fiction")
Genre.find_or_create_by(name: "Romance")
Genre.find_or_create_by(name: "Horror")
Genre.find_or_create_by(name: "Travel")
Genre.find_or_create_by(name: "Classics")
Genre.find_or_create_by(name: "Medicine")
